services:
  selenium-hub:
    image: selenium/hub:4.21.0
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.21.0
    shm_size: 2g
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    deploy:
      replicas: 3

  testng-runner:
    build:
      context: .
    container_name: testng-runner
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - RUN_IN_DOCKER=true
    volumes:
      - /c/Users/lenovo/Desktop/Comcate/cyberdyne-selenium-ce/ExtentReports:/app/ExtentReports
      - /c/Users/lenovo/Desktop/Comcate/cyberdyne-selenium-ce/TestData:/app/TestData
